version: '2'
services:
    drillthedata-app:
        image: drillthedata
        external_links:
            - drillthedata-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/DrillTheData
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    drillthedata-postgresql:
        extends:
            file: postgresql.yml
            service: drillthedata-postgresql
